/* Generated By:JavaCC: Do not edit this line. cmmJavaCCConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
/**
 * 含常量的辅助性接口。 
 * @author myr
 *
 */
public interface cmmJavaCCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IP = 7;
  /** RegularExpression Id. */
  int ACCESSLIST = 8;
  /** RegularExpression Id. */
  int EXTENDED = 9;
  /** RegularExpression Id. */
  int PERMIT = 10;
  /** RegularExpression Id. */
  int DENY = 11;
  /** RegularExpression Id. */
  int ANY = 12;
  /** RegularExpression Id. */
  int HOST = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int ACCESSLISTNAME = 15;
  /** RegularExpression Id. */
  int IPADDR = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int RULEORDER = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"ip\"",
    "\"access-list\"",
    "\"extended\"",
    "\"permit\"",
    "\"deny\"",
    "\"any\"",
    "\"host\"",
    "<LETTER>",
    "<ACCESSLISTNAME>",
    "<IPADDR>",
    "<DIGIT>",
    "<RULEORDER>",
    "\"{\"",
    "\"}\"",
  };

}
